# Generated by Django 5.2 on 2025-06-05 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecializationPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('DERMATOLOGIST', 'Dermatologist'), ('NEUROLOGIST', 'Neurologist'), ('PEDIATRICIAN', 'Pediatrician'), ('CARDIOLOGIST', 'Cardiologist'), ('GASTROENTEROLOGIST', 'Gastroenterologist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('ENDOCRINOLOGIST', 'Endocrinologist'), ('FAMILY_MEDICINE', 'Family Medicine'), ('GENERAL_SURGERY', 'General Surgery'), ('NEPHROLOGIST', 'Nephrologist')], max_length=50, unique=True)),
                ('price', models.IntegerField(default=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_session_id', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='appointments.appointment')),
            ],
        ),
    ]
