# Generated by Django 5.2 on 2025-05-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_amount_payment_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent_id',
            new_name='stripe_payment_session_id',
        ),
    ]
