# Generated by Django 5.2 on 2025-05-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('list_article', 'Can list articles')]},
        ),
    ]
