# Generated by Django 5.2.1 on 2025-06-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={
                "ordering": ["-date"],
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="admin_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="admin_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="resolved_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("IN_PROGRESS", "In Progress"),
                    ("RESOLVED", "Resolved"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="issue",
            name="title",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
