version: '3.8'

services:
  db:
    image: postgres:14
    # Removed persistent volume for tests to ensure a clean database each time
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=takecare_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    # Use tmpfs for faster test database operations
    tmpfs: /var/lib/postgresql/data

  redis:
    image: redis:7
    command: redis-server --appendonly no
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: bash /app/docker/entrypoint_test.sh
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SETTINGS_MODULE=TakeCare.settings_test
      - POSTGRES_DB=takecare_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379