version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=takecare
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - takecare_network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=takecare
      - POSTGRES_USER=macbook
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    networks:
      - takecare_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - takecare_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  takecare_network:
    driver: bridge