version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/staticfiles
      - ./media:/app/media
    networks:
      - takecare_network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - takecare_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - takecare_network

volumes:
  postgres_data:
  redis_data:

networks:
  takecare_network:
    driver: bridge