version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=takecare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_DEBUG=True
      - STATIC_ROOT=/app/staticfiles
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - /app/staticfiles
      - media_volume:/app/media
    networks:
      - takecare_network

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_DB=takecare
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    networks:
      - takecare_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - takecare_network

volumes:
  postgres_data:
  redis_data:
  media_volume:

networks:
  takecare_network:
    driver: bridge