# Generated by Django 5.2 on 2025-05-08 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialist_type', models.CharField(choices=[('DERMATOLOGIST', 'Dermatologist'), ('NEUROLOGIST', 'Neurologist'), ('PEDIATRICIAN', 'Pediatrician'), ('CARDIOLOGIST', 'Cardiologist'), ('GASTROENTEROLOGIST', 'Gastroenterologist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('ENDOCRINOLOGIST', 'Endocrinologist'), ('FAMILY_MEDICINE', 'Family Medicine'), ('GENERAL_SURGERY', 'General Surgery'), ('NEPHROLOGIST', 'Nephrologist')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_used', models.BooleanField(default=False)),
                ('issuing_doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_as_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='referrals.referral')),
            ],
        ),
    ]
