# Generated by Django 4.2.17 on 2025-04-01 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "specialist_type",
                    models.CharField(
                        choices=[
                            ("Dermatologist", "Dermatologist"),
                            ("Neurologist", "Neurologist"),
                            ("Pediatrician", "Pediatrician"),
                            ("Cardiologist", "Cardiologist"),
                            ("Gastroenterologist", "Gastroenterologist"),
                            ("Ophthalmologist", "Ophthalmologist"),
                            ("Endocrinologist", "Endocrinologist"),
                            ("Family medicine", "Family Medicine"),
                            ("General surgery", "General Surgery"),
                            ("Nephrologist", "Nephrologist"),
                        ],
                        max_length=50,
                    ),
                ),
                ("issue_date", models.DateField()),
                ("expiration_date", models.DateField()),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                    ),
                ),
            ],
        ),
    ]
