# Generated by Django 5.2 on 2025-05-07 20:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialist_type', models.CharField(choices=[('DERMATOLOGIST', 'Dermatologist'), ('NEUROLOGIST', 'Neurologist'), ('PEDIATRICIAN', 'Pediatrician'), ('CARDIOLOGIST', 'Cardiologist'), ('GASTROENTEROLOGIST', 'Gastroenterologist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('ENDOCRINOLOGIST', 'Endocrinologist'), ('FAMILY_MEDICINE', 'Family Medicine'), ('GENERAL_SURGERY', 'General Surgery'), ('NEPHROLOGIST', 'Nephrologist')], max_length=50)),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('is_used', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
