# Generated by Django 5.1.7 on 2025-05-07 19:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "DOCTOR"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_as_doctor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="referral",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"role": "PATIENT"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_as_patient",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ReferralDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("diagnosis", models.CharField(max_length=255)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("additional_info", models.TextField(blank=True, null=True)),
                (
                    "referral",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="referrals.referral",
                    ),
                ),
            ],
        ),
    ]