# Generated by Django 5.2 on 2025-04-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
