# Generated by Django 5.2 on 2025-05-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'permissions': [('list_referral', 'Can list referrals'), ('search_referral', 'Can search referrals')]},
        ),
    ]
