# Generated by Django 5.2 on 2025-05-07 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referral_doctor_referral_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='doctor',
        ),
    ]
