# Generated by Django 5.2 on 2025-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_alter_referral_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='specialist_type',
            field=models.CharField(choices=[('DERMATOLOGIST', 'Dermatologist'), ('NEUROLOGIST', 'Neurologist'), ('PEDIATRICIAN', 'Pediatrician'), ('CARDIOLOGIST', 'Cardiologist'), ('GASTROENTEROLOGIST', 'Gastroenterologist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('ENDOCRINOLOGIST', 'Endocrinologist'), ('FAMILY_MEDICINE', 'Family Medicine'), ('GENERAL_SURGERY', 'General Surgery'), ('NEPHROLOGIST', 'Nephrologist')], max_length=50),
        ),
    ]
