# Generated by Django 5.2 on 2025-05-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referral_doctor_referral_notes_and_more'),
    ]

    operations = [
        # Use RunPython to safely check if the column exists before trying to remove it
        migrations.RunSQL(
            # SQL to check if column exists and drop it if it does
            """
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'referrals_referral' AND column_name = 'doctor_id'
                ) THEN
                    ALTER TABLE referrals_referral DROP COLUMN doctor_id;
                END IF;
            END $$;
            """,
            # No reverse SQL needed
            ""
        ),
        # Add the issuing_doctor field if it doesn't already exist
        migrations.RunSQL(
            # SQL to check if column doesn't exist and add it if needed
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns 
                    WHERE table_name = 'referrals_referral' AND column_name = 'issuing_doctor_id'
                ) THEN
                    ALTER TABLE referrals_referral ADD COLUMN issuing_doctor_id uuid NULL REFERENCES accounts_user(id) ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            # No reverse SQL needed
            ""
        ),
    ]
