# Generated by Django 5.2 on 2025-04-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referral_is_used'),
        ('referrals', '0003_alter_referral_specialist_type'),
    ]

    operations = [
    ]
