# Generated by Django 4.2.17 on 2025-04-01 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("condition", models.TextField()),
                ("treatment", models.TextField()),
                ("notes", models.TextField()),
                ("file", models.FileField(upload_to="medical_records/")),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records_as_doctor",
                        to="accounts.user",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records_as_patient",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
    ]
