# Generated by Django 5.2 on 2025-05-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'permissions': [('list_medicalrecord', 'Can list medical records'), ('search_medicalrecord', 'Can search medical records')]},
        ),
    ]
