# Generated by Django 5.2.1 on 2025-06-04 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("personal_id", models.CharField(max_length=50, unique=True)),
                ("birth_date", models.DateField()),
                ("gender", models.CharField(max_length=10)),
                ("address", models.TextField()),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PATIENT", "Patient"),
                            ("DOCTOR", "Doctor"),
                            ("ADMIN", "Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="avatars/default_avatar.jpg",
                        null=True,
                        upload_to="avatars/",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("block_user", "Can block or unblock a user"),
                    ("list_user", "Can see the whole or partial list of all users"),
                    (
                        "debugSpecialization_user",
                        "Can debug the specialization of a doctor",
                    ),
                    ("searchPatient_user", "Can search for a patient"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("license_uri", models.URLField(unique=True)),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("DERMATOLOGIST", "Dermatologist"),
                            ("NEUROLOGIST", "Neurologist"),
                            ("PEDIATRICIAN", "Pediatrician"),
                            ("CARDIOLOGIST", "Cardiologist"),
                            ("GASTROENTEROLOGIST", "Gastroenterologist"),
                            ("OPHTHALMOLOGIST", "Ophthalmologist"),
                            ("ENDOCRINOLOGIST", "Endocrinologist"),
                            ("FAMILY_MEDICINE", "Family Medicine"),
                            ("GENERAL_SURGERY", "General Surgery"),
                            ("NEPHROLOGIST", "Nephrologist"),
                        ],
                        default="PEDIATRICIAN",
                        max_length=50,
                    ),
                ),
                ("work_address", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
