# Generated by Django 5.2 on 2025-04-24 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_doctorprofile_patientprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('block_user', 'Can block or unblock a user')]},
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('DERMATOLOGIST', 'Dermatologist'), ('NEUROLOGIST', 'Neurologist'), ('PEDIATRICIAN', 'Pediatrician'), ('CARDIOLOGIST', 'Cardiologist'), ('GASTROENTEROLOGIST', 'Gastroenterologist'), ('OPHTHALMOLOGIST', 'Ophthalmologist'), ('ENDOCRINOLOGIST', 'Endocrinologist'), ('FAMILY_MEDICINE', 'Family Medicine'), ('GENERAL_SURGERY', 'General Surgery'), ('NEPHROLOGIST', 'Nephrologist')], default='PEDIATRICIAN', max_length=50),
        ),
    ]
