# Generated by Django 5.2 on 2025-05-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('block_user', 'Can block or unblock a user'), ('list_user', 'Can see the whole or partial list of all users'), ('debugSpecialization_user', 'Can debug the specialization of a doctor'), ('searchPatient_user', 'Can search for a patient')]},
        ),
    ]
