# Generated by Django 5.2 on 2025-04-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('block_user', 'Can block or unblock a user'), ('list_user', 'Can see the whole or partial list of all users')]},
        ),
    ]
