# Generated by Django 5.2 on 2025-04-28 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
        ('accounts', '0004_alter_user_options'),
    ]

    operations = [
    ]
