# Generated by Django 4.2.17 on 2025-04-01 18:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medication_name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=255)),
                ("notes", models.TextField()),
                ("issue_date", models.DateField()),
                ("expiration_date", models.DateField()),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions_as_doctor",
                        to="accounts.user",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions_as_patient",
                        to="accounts.user",
                    ),
                ),
            ],
        ),
    ]
