# Generated by Django 5.2 on 2025-04-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_doctorprofile_patientprofile'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_as_doctor', to='accounts.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_as_patient', to='accounts.patientprofile'),
        ),
    ]
