# Generated by Django 5.2 on 2025-05-22 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'permissions': [('list_prescription', 'Can list prescriptions'), ('search_prescription', 'Can search prescriptions')]},
        ),
    ]
