# Generated by Django 5.1.7 on 2025-04-18 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="dosage",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="medication_name",
        ),
        migrations.AlterField(
            model_name="prescription",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="PrescriptionMedication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medication_name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=255)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medications",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
        ),
    ]
