# Generated by Django 5.1.7 on 2025-04-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prescriptions", "0002_remove_prescription_dosage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="notes",
            field=models.TextField(),
        ),
    ]
