# Generated by Django 5.2 on 2025-04-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_alter_prescription_doctor_alter_prescription_patient'),
        ('prescriptions', '0003_alter_prescription_notes'),
    ]

    operations = [
    ]
