# Generated by Django 5.2.1 on 2025-06-04 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("referrals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateTimeField(db_column="date")),
                ("duration", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Cancelled", "Cancelled"),
                            ("Booked", "Booked"),
                        ]
                    ),
                ),
                (
                    "referal_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DERMATOLOGIST", "Dermatologist"),
                            ("NEUROLOGIST", "Neurologist"),
                            ("PEDIATRICIAN", "Pediatrician"),
                            ("CARDIOLOGIST", "Cardiologist"),
                            ("GASTROENTEROLOGIST", "Gastroenterologist"),
                            ("OPHTHALMOLOGIST", "Ophthalmologist"),
                            ("ENDOCRINOLOGIST", "Endocrinologist"),
                            ("FAMILY_MEDICINE", "Family Medicine"),
                            ("GENERAL_SURGERY", "General Surgery"),
                            ("NEPHROLOGIST", "Nephrologist"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        limit_choices_to={"role": "DOCTOR"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments_as_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "PATIENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments_as_patient",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referral",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="referrals.referral",
                    ),
                ),
                (
                    "appointment_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appointments.appointmentslot",
                    ),
                ),
            ],
        ),
    ]
