# Generated by Django 5.1.4 on 2025-04-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Cancelled', 'Cancelled'), ('Booked', 'Booked'), ('Finished', 'Finished')]),
        ),
    ]
