# Generated by Django 5.2 on 2025-04-21 14:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_doctorprofile_patientprofile'),
        ('appointments', '0001_initial'),
        ('referrals', '0002_alter_referral_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_patient', to='accounts.patientprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='referral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='referrals.referral'),
        ),
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Cancelled', 'Cancelled'), ('Booked', 'Booked'), ('Finished', 'Finished')])),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_doctor', to='accounts.doctorprofile')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_slot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentslot'),
            preserve_default=False,
        ),
    ]
