# Generated by Django 5.1.4 on 2025-04-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
