# Generated by Django 5.1.4 on 2025-04-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_duration_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='duration_minutes',
            new_name='duration',
        ),
    ]
