# Generated by Django 5.1.4 on 2025-04-10 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_appointment_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentslot'),
        ),
    ]
