# Generated by Django 5.2 on 2025-04-19 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_appointment_slot'),
        ('referrals', '0002_referral_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='referal_type',
            field=models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Cardiologist', 'Cardiologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Endocrinologist', 'Endocrinologist'), ('Family medicine', 'Family Medicine'), ('General surgery', 'General Surgery'), ('Nephrologist', 'Nephrologist')], null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='referral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='referrals.referral'),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Cancelled', 'Cancelled'), ('Booked', 'Booked')]),
        ),
    ]
