# Generated by Django 5.2 on 2025-04-22 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointmentslot_referal_type_and_more'),
        ('referrals', '0002_referral_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='referral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='referrals.referral'),
        ),
        migrations.AlterField(
            model_name='appointmentslot',
            name='referal_type',
            field=models.CharField(blank=True, choices=[('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Pediatrician', 'Pediatrician'), ('Cardiologist', 'Cardiologist'), ('Gastroenterologist', 'Gastroenterologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Endocrinologist', 'Endocrinologist'), ('Family medicine', 'Family Medicine'), ('General surgery', 'General Surgery'), ('Nephrologist', 'Nephrologist')], null=True),
        ),
    ]
