# Generated by Django 5.2 on 2025-04-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_date_and_more'),
        ('appointments', '0009_alter_appointment_referral_and_more'),
    ]

    operations = [
    ]
