# Generated by Django 5.2.1 on 2025-06-04 20:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(default="", max_length=255)),
                ("message", models.TextField(default="System notification")),
                ("is_encrypted", models.BooleanField(default=False)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("REFERRAL", "Referral"),
                            ("PRESCRIPTION", "Prescription"),
                            ("APPOINTMENT", "Appointment"),
                            ("SYSTEM", "System"),
                            ("MEDICAL", "Medical"),
                            ("ISSUE", "Issue"),
                            ("MESSAGE", "Message"),
                            ("MEDICAL_RECORD", "Medical Record"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("severity", models.CharField(default="MEDIUM", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNREAD", "Unread"),
                            ("READ", "Read"),
                            ("DELETED", "Deleted"),
                        ],
                        default="UNREAD",
                        max_length=10,
                    ),
                ),
                ("delivery_channel", models.CharField(default="IN_APP", max_length=10)),
                ("retry_count", models.SmallIntegerField(default=0)),
                ("max_retries", models.SmallIntegerField(default=3)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
