# Generated by Django 5.2 on 2025-05-21 21:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(default='System notification')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('REFERRAL', 'Referral'), ('PRESCRIPTION', 'Prescription'), ('APPOINTMENT', 'Appointment'), ('SYSTEM', 'System'), ('MEDICAL', 'Medical')], default='SYSTEM', max_length=20)),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('DELETED', 'Deleted')], default='UNREAD', max_length=10)),
                ('related_object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sensitive_data', models.TextField(blank=True, null=True)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('last_delivery_attempt', models.DateTimeField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
