# Generated by Django 5.2 on 2025-05-21 22:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        # First, check if 'created_at' exists and rename it to 'date'
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'notifications_notification'
                    AND column_name = 'created_at'
                ) THEN
                    ALTER TABLE notifications_notification RENAME COLUMN created_at TO date;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'notifications_notification'
                    AND column_name = 'date'
                ) THEN
                    ALTER TABLE notifications_notification RENAME COLUMN date TO created_at;
                END IF;
            END $$;
            """
        ),
        # Then, add 'date' if it doesn't exist
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'notifications_notification'
                    AND column_name = 'date'
                ) THEN
                    ALTER TABLE notifications_notification ADD COLUMN date TIMESTAMP WITH TIME ZONE DEFAULT NOW();
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_name = 'notifications_notification'
                    AND column_name = 'date'
                ) THEN
                    ALTER TABLE notifications_notification DROP COLUMN date;
                END IF;
            END $$;
            """
        ),
    ]
