# Generated by Django 5.2 on 2025-05-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20250521_2205'),
    ]

    operations = [
        # This is a fake migration that won't modify the database
        # It just ensures our model matches the actual database schema
    ]
