name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      POSTGRES_DB: github_actions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      REDIS_HOST: localhost
      DJANGO_SECRET_KEY: testing-key-not-for-production
      DJANGO_DEBUG: True
      DJANGO_SETTINGS_MODULE: TakeCare.settings
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Initialize PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        
    - name: Check for missing migrations
      run: |
        python manage.py makemigrations --check --dry-run
        
    - name: Apply migrations
      run: |
        python manage.py migrate --no-input
        
    - name: Run Tests
      run: |
        python manage.py test chat.tests -v 2