name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      POSTGRES_DB: github_actions_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      REDIS_HOST: localhost
      DJANGO_SECRET_KEY: testing-key-not-for-production
      DJANGO_DEBUG: True
      DJANGO_SETTINGS_MODULE: TakeCare.settings
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: github_actions_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify PostgreSQL Connection
      run: |
        apt-get update && apt-get install -y postgresql-client
        PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -c '\conninfo'
        
    - name: Run Migrations
      run: |
        python manage.py migrate --check
        python manage.py makemigrations --check
        python manage.py migrate
        
    - name: Run Tests
      run: |
        python manage.py test chat.tests -v 2