name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up environment
      env:
        DJANGO_SETTINGS_MODULE: TakeCare.settings
        POSTGRES_DB: github_actions
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        REDIS_HOST: localhost
        DJANGO_SECRET_KEY: testing-key-not-for-production
        DJANGO_DEBUG: True
      run: |
        python -c "
          import django
          from django.conf import settings
          django.setup()
          print('Django configured with apps:', settings.INSTALLED_APPS)
        "
        
    - name: Run Migrations
      env:
        DJANGO_SETTINGS_MODULE: TakeCare.settings
        POSTGRES_DB: github_actions
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        REDIS_HOST: localhost
        DJANGO_SECRET_KEY: testing-key-not-for-production
        DJANGO_DEBUG: True
      run: |
        python manage.py check
        python manage.py makemigrations
        python manage.py migrate
        
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: TakeCare.settings
        POSTGRES_DB: github_actions
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        REDIS_HOST: localhost
        DJANGO_SECRET_KEY: testing-key-not-for-production
        DJANGO_DEBUG: True
      run: |
        python manage.py test chat.tests -v 2